
spring:
  datasource:
    hikari:
      connection-timeout: '20000'
      maximum-pool-size: '5'
    password: caleb2020
    username: servicecaleb
    url: jdbc:postgresql://localhost:5432/caleb
  application:
    name: RCaleb
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'true'
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        sql: DEBUG
server:
  servlet:
    context-path: /RCaleb-crud
  port: 8081
  eureka:
    instance:
      instance-id: "${spring.application.name}:${random.value}"
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
